### PR TITLE
[#3] Set up Firebase including Firebase Crashlytic plugin

### LINKED ISSUE #3: [Chore] Set up firebase project
## Why

To deploy the app for testing, we must make use of Firebase App Testing

## Acceptance Criteria

- [ ] Create a new Firebase project for the IC
  - Deployment to Firebase will be handled in #5

### PR DESCRIPTION
**Pull request by lydiasama**
- Closes #3

## What happened 👀

- Set up Firebase follow this document: [Firebase CLI](https://firebase.google.com/docs/cli?authuser=0&hl=en#mac-linux-npm), [Add Firebase to Flutter App](https://firebase.google.com/docs/flutter/setup?platform=ios)
- Install Firebase Crashlytic plugin: https://firebase.google.com/docs/crashlytics/get-started?platform=flutter

## Insight 📝

- After setting up the Firebase plugin, we need to update the Podfile and pod compatible version. Ref here: https://stackoverflow.com/a/67201729

## Proof Of Work 📹

The Firebase console URL is [here](https://console.firebase.google.com/u/0/project/flutter-ic-lydia-ryan/overview)

Screenshot 2566-03-09 at 7 44 47 PM

Screenshot 2566-03-09 at 7 44 41 PM

The application can build and run successfully.

Screenshot 2566-03-09 at 8 14 31 PM

### CODE REVIEW

**Comment by markgravity** [comment]
Can you check the CI/CD error, please? 🙏

**Comment by lydiasama** [comment]
@markgravity @ryan-conway I think the CI failed because there is changed file on this step:

Screenshot 2566-03-14 at 11 13 53 AM

Any idea how to fix this? 🙏🏻

**Comment by ryan-conway** [comment]
@lydiasama it failed because we need to format `firebase_options.dart`, to do that we can run the following command in terminal 😄 
`flutter format lib/firebase_options.dart`

**Comment by lydiasama** [comment]
@ryan-conway Oh I thought it would run format by the CI. 🤔  Thanks for your help.

**Review by markgravity — APPROVED** [review]

**Review by ryan-conway — APPROVED** [review]

**Comment by lydiasama** [comment]
@ryan-conway I've updated the Bundle ID for iOS app to be production. 🙏🏻

**Pull request merged**
